### ISSUE TITLE
Error in t == curr_t :    comparison (1) is possible only for atomic and list types

### ISSUE THREAD

**Issue by bmunn99** [dataMaster-Kris/dStruct#1]
Trying to run `dStructome` function and I encountered this error.
I have my list of dataframes titled "list_WT_E638A_P2", with three dataframes respectively titled "WT", "E638A", and "P2". I've renamed the four columns in each to A1, A2, B1, and B2. The values in each column, however, are all the same, as I am testing the dStruct functions without actual replicates yet. Would that interfere with running `dStruct` or `dStructome`? Because when I do run `dStructome` it looks like this: 
<img width="552" alt="Screenshot 2023-06-22 at 3 31 59 PM" src="https://github.com/dataMaster-Kris/dStruct/assets/115659013/bd1512e5-a71d-440d-bd15-d5980c8cf3f5">

I then run `dStructurome` and it gives me "Error in t == curr_t : 
  comparison (1) is possible only for atomic and list types"

**Comment by dataMaster-Kris** [comment]
Hi, sorry for the late reply. With your test data, you will not find any differential regions, which is likely causing the issue. You can instead try to run with the test data that comes with the package.
